apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    name: prometheus-pv # name can be anything
spec:
  storageClassName: prometheus # same storage class as pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.9.2 # NFS server IP address 
    path: "/Public/k8s_storage/prometheus/"   # NFS share location 

