apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus-server
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s 
      evaluation_interval: 15s 
    scrape_configs:
     
     - job_name: 'mysql'
       static_configs:
       - targets: ['192.168.3.18:9104']