apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus-server
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000